apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessing-deployment
  labels:
    app: orderprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderprocessing
  template:
    metadata:
      labels:
        app: orderprocessing
    spec:
      containers:
      - name: orderprocessing
        image: freakydeveloper007/orderprocessing:v3
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_HOST
            value: mysql-service
          - name: MYSQL_USER_NAME
            valueFrom:
              secretKeyRef:
                  name: secret
                  key: MYSQL_USER_NAME
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: secret
                  key: MYSQL_USER_PASSWORD
          - name: PAYMENT_SERVER_PORT
            value: "80"
          - name: PAYMENT_API_HOST
            value: 34.134.186.195
          - name: PAYMENT_API_KEY
            valueFrom:
              secretKeyRef:
                  name: secret
                  key: PAYMENT_API_KEY

            