FROM openjdk:11
EXPOSE 8080
ADD ./build/libs/OrderProcessing-0.0.1-SNAPSHOT.jar /srv/OrderProcessing-0.0.1-SNAPSHOT.jar
CMD java -jar /srv/OrderProcessing-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev

